'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFKC').trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ');
let state={cards:[],history:[],trash:[],settings:{}},currentLookup=null,editId=null,queue=[],sessionTotal=0,article=null;
let version=0,lookingUp=false,active='home',practice=false,session=false,answered=false,ratingBusy=false,lastDraftWord='',libraryFilter='all',showArticleZh=false,calendarMonthOffset=0;
const labels=['非常困難','困難','尚可','簡單'],descriptions=['忘記了或答錯','想很久才想起','稍微想一下就答對','立刻想起，很確定'];
async function api(url,body,retry=true){
 let r;try{r=await fetch('/api/'+url+(url.includes('?')?'&':'?')+'_request='+Date.now()+'-'+Math.random().toString(36).slice(2),{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-App-Token':$('meta[name="app-token"]').content},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(45000),cache:'no-store'});}catch{throw Error('連線中斷，請重新開啟「開啟拾字新版」再重試。填寫內容已保留。');}
 if(r.status===403&&retry){const html=await(await fetch('/?session='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(5000)})).text();const meta=new DOMParser().parseFromString(html,'text/html').querySelector('meta[name="app-token"]');if(meta){$('meta[name="app-token"]').content=meta.content;return api(url,body,false);}}
 const d=await r.json();if(!r.ok)throw Error(d.error||'操作失敗，請再試一次。');return d;
}
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500);}
function status(id,s,error=false){const el=$(id);el.textContent=s;el.hidden=!s;el.classList.toggle('error',error);}
async function run(fn,button,target){if(button)button.disabled=true;try{return await fn();}catch(e){if(target)status(target,e.message,true);else toast(e.message);}finally{if(button)button.disabled=false;}}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const date=ms=>new Date(ms).toLocaleString('zh-TW',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const safeLink=s=>{try{const u=new URL(s);return u.protocol==='https:'?esc(u.href):'#';}catch{return '#';}};
function source(c){return c.sourceUrl?`<a href="${safeLink(c.sourceUrl)}" target="_blank" rel="noopener">${esc(c.source)} ↗</a>`:esc(c.source||'自行記錄');}
function due(){return state.cards.filter(c=>c.due<=Date.now()).sort((a,b)=>a.due-b.due);}
function cardRating(c){return latestRating(c,state.history);}
function nextDue(){const c=state.cards.filter(c=>c.due>Date.now()).sort((a,b)=>a.due-b.due)[0];return c?'下次到期：'+date(c.due):'新增一個今天遇見的字，就可以開始。';}
const dayKey=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
function learningStreak(){
 const learned=new Set(state.history.map(h=>h.day||dayKey(new Date(h.at))));if(!learned.size)return 0;
 let cursor=new Date(today()+'T12:00:00+08:00'),count=0;if(!learned.has(dayKey(cursor)))cursor.setUTCDate(cursor.getUTCDate()-1);
 while(learned.has(dayKey(cursor))){count++;cursor.setUTCDate(cursor.getUTCDate()-1);}return count;
}
function weekStats(){
 const current=today(),weekday=new Date(current+'T12:00:00+08:00').getUTCDay(),monday=new Date(current+'T00:00:00+08:00');monday.setUTCDate(monday.getUTCDate()-((weekday+6)%7));
 return state.history.filter(h=>h.at>=monday.getTime()).length;
}
function renderCalendar(){
 const current=today(),[currentYear,currentMonth]=current.split('-').map(Number),view=new Date(Date.UTC(currentYear,currentMonth-1+calendarMonthOffset,1)),year=view.getUTCFullYear(),month=view.getUTCMonth(),leading=(view.getUTCDay()+6)%7,start=new Date(Date.UTC(year,month,-leading+1)),learned=new Set(state.history.map(h=>h.day||dayKey(new Date(h.at)))),cells=[];
 $('#calendar-month').textContent=`${year} 年 ${month+1} 月`;$('#learning-calendar').setAttribute('aria-label',`${year} 年 ${month+1} 月學習紀錄`);
 for(let index=0;index<42;index++){const d=new Date(start);d.setUTCDate(start.getUTCDate()+index);const key=d.toISOString().slice(0,10),inMonth=d.getUTCMonth()===month,isToday=key===current,done=learned.has(key);cells.push(`<div class="calendar-day${inMonth?'':' outside'}${isToday?' today':''}${done?' practiced':''}" aria-label="${key}${done?'，已練習':''}${isToday?'，今天':''}"><span>${d.getUTCDate()}</span>${done?'<i class="ph ph-check" aria-hidden="true"></i>':'<b aria-hidden="true"></b>'}</div>`);}$('#learning-calendar').innerHTML=cells.join('');
 const streak=learningStreak();$('#streak-label').textContent=streak?`連續 ${streak} 天`:'今天開始';
}
function stats(){
 const doneToday=new Set(state.history.filter(h=>(h.day||dayKey(new Date(h.at)))===today()).map(h=>h.id)).size,streak=learningStreak(),weekly=weekStats(),weeklyGoal=50,percent=Math.min(100,Math.round(weekly/weeklyGoal*100));
 $('#due-count').textContent=due().length;$('#done-count').textContent=doneToday;$('#total-count').textContent=state.cards.length;$('#weekly-percent').textContent=percent+'%';$('#weekly-count').textContent=`${weekly} / ${weeklyGoal} 張`;$('#weekly-meter').value=Math.min(weekly,weeklyGoal);$('#mastered-count').textContent=state.cards.filter(c=>cardRating(c)===3).length;$('#learning-days').textContent=new Set(state.history.map(h=>h.day||dayKey(new Date(h.at)))).size;renderCalendar();
 const dueCount=due().length;$('#review-card-title').textContent=session&&queue.length?'繼續本輪複習':dueCount?'今天待複習':state.cards.length?'今天已完成':'開始收集單字';
 $('#review-hint').textContent=dueCount?`今天有 ${dueCount} 個單字待複習，每輪最多 20 張。`:nextDue();$('#practice-review').hidden=!state.cards.length;
}
async function refresh(){state=await api('state');state.trash||=[];stats();$('#service-status').textContent=`出版社字典：${state.settings.mw?'已設定（查字時驗證）':'未連接'}　／　自動翻譯：${state.settings.deepl?'已設定（翻譯時驗證）':'使用內建翻譯'}`;$('#storage-label').textContent=state.storage==='cloud'?'CLOUD · 雲端同步保存':'LOCAL · 資料保存在這台電腦';$('#backup-description').textContent=state.storage==='cloud'?'單字和複習進度已保存在雲端。仍可偶爾下載備份自行保管。':'單字和複習進度保存在這台電腦。偶爾下載一份備份，換電腦或資料遺失時就能還原。';renderLibrary();}
function view(id){active=id;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==id);document.querySelectorAll('nav button').forEach(b=>{const yes=b.dataset.view===id||(id==='review'&&b.dataset.view==='home');b.classList.toggle('active',yes);if(yes)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(id==='reading')loadNews();if(id==='library')renderLibrary();window.scrollTo(0,0);const h=$('#'+id+' h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
$('#calendar-prev').onclick=()=>{calendarMonthOffset--;renderCalendar();};$('#calendar-next').onclick=()=>{calendarMonthOffset++;renderCalendar();};$('#calendar-today').onclick=()=>{calendarMonthOffset=0;renderCalendar();};
$('#date').textContent=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date())+' · 台灣時間';
function draft(){return {word:$('#word').value,meaning:$('#meaning').value,example:$('#example').value,note:$('#note').value,editId,currentLookup};}
function saveDraft(){lastDraftWord=norm($('#word').value);try{localStorage.setItem('word-garden-draft',JSON.stringify(draft()));}catch{}}
function clearEdit(){editId=null;currentLookup=null;version++;$('#word').value='';$('#save-form').reset();$('#save-form').hidden=true;$('#extras').open=false;$('#manual-meaning').open=false;$('#save-word').hidden=false;$('#lookup-result').innerHTML='';$('#edit-title').textContent='這次想記住的是…';$('#save-form button.primary').textContent='儲存單字';status('#form-status','');$('#saved-actions').hidden=true;saveDraft();}
const speakerIcon='<svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true"><path d="M11 4 6 8H3v8h3l5 4V4ZM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';
function audioButton(id,word){return '<button type="button" class="speaker" id="'+id+'" aria-label="朗讀 '+esc(word)+'" title="聽發音">'+speakerIcon+'</button>';}
function meanings(c){
 const lines=(c.dictionaryNotes||'').split('\n').filter(Boolean),main=[],extra=[];
 for(const line of lines){const parts=line.split(' · '),m=parts.length>1?parts[1]:line;if(/專門用法/.test(parts[0])||(c.word==='duty'&&m==='尊敬'))extra.push(line);else main.push(m);}
 if(!main.length)main.push(...String(c.meaning||'').split(/\n|／/));
 return {main:c.primaryMeaning||[...new Set(main.filter(Boolean))].join('／'),extra:[...new Set(extra)].join('；')};
}
function renderLookup(d){
 const existing=state.cards.find(c=>c.word===d.word),notes=d.dictionaryNotes||(d.senses||[]).map(s=>[s.part,s.meaning,s.english].filter(Boolean).join(' · ')).join('\n');
 const m=meanings({...d,dictionaryNotes:notes,meaning:$('#meaning').value});
 $('#meaning').value=m.main;$('#save-form').hidden=false;
 $('#lookup-result').innerHTML='<div class="word-heading"><h2>'+esc(d.word)+'</h2>'+audioButton('lookup-speak',d.word)+'</div>'+(d.phonetic?'<p class="source">'+esc(d.phonetic)+'</p>':'')+'<p class="compact-meaning">'+esc(m.main||'查不到解釋，可在補充內容自行填寫。')+'</p>'+(m.extra?'<details class="source"><summary>特定用法與待核對解釋</summary><p>'+esc(m.extra)+'</p></details>':'')+(existing&&editId!==existing.id?'<p class="collected">✓ 已收集</p><button type="button" class="secondary" id="edit-existing">編輯這張卡</button>':'');
 $('#lookup-source').innerHTML=source(d)+(d.warning?'<p>'+esc(d.warning)+'</p>':'');
 $('#lookup-speak').onclick=()=>speak(d.word);$('#save-word').hidden=!!existing&&editId!==existing.id;
 if($('#edit-existing'))$('#edit-existing').onclick=()=>editCard(existing);
 if(!m.main){$('#extras').open=true;$('#manual-meaning').open=true;}
 if($('#example').value)$('#extras').open=true;
}
$('#lookup-form').onsubmit=e=>{e.preventDefault();const v=++version,w=norm($('#word').value);if(!/^[a-z][a-z '-]{0,79}$/.test(w)){status('#form-status','請輸入英文單字或片語，不需要加編號。',true);$('#word').focus();return;}lookingUp=true;$('#save-form button.primary').disabled=true;currentLookup=null;status('#form-status','');$('#save-form').hidden=true;status('#form-status','正在查詢字義…');
 run(async()=>{const d=await api('lookup?word='+encodeURIComponent(w));if(v!==version||norm($('#word').value)!==w)return;currentLookup=d;status('#form-status','');renderLookup(d);saveDraft();},e.submitter,'#form-status').finally(()=>{if(v===version){lookingUp=false;$('#save-form button.primary').disabled=false;if(!currentLookup){$('#save-form').hidden=false;$('#extras').open=true;$('#manual-meaning').open=true;$('#lookup-result').textContent='查詢未完成，可重試或自行填寫解釋。';}}});
};
$('#word').oninput=()=>{const typed=$('#word').value;$('#save-word').hidden=false;$('#extras').open=false;$('#manual-meaning').open=false;if(lastDraftWord&&norm(typed)!==lastDraftWord){$('#meaning').value='';$('#example').value='';$('#note').value='';}version++;lookingUp=false;$('#saved-actions').hidden=true;$('#save-form').hidden=true;$('#save-form button.primary').disabled=false;currentLookup=null;$('#lookup-result').innerHTML='';status('#form-status','');saveDraft();};
['#meaning','#example','#note'].forEach(id=>$(id).addEventListener('input',saveDraft));$('#meaning').addEventListener('input',()=>{if(currentLookup)currentLookup.primaryMeaning=$('#meaning').value;const preview=$('#lookup-result .compact-meaning');if(preview)preview.textContent=$('#meaning').value;saveDraft();});$('#clear-edit').onclick=()=>{clearEdit();$('#word').focus();};
$('#save-form').onsubmit=e=>{e.preventDefault();if(lookingUp)return;const p=draft(),savingId=editId;if(!p.meaning.trim()){status('#form-status','請先查詢單字，或在補充內容填寫解釋。',true);$('#extras').open=true;$('#manual-meaning').open=true;$('#meaning').focus();return;}if(!norm(p.word)){status('#form-status','請先在上方填入要儲存的英文單字。',true);$('#word').focus();return;}run(async()=>{const d=p.currentLookup&&p.currentLookup.word===norm(p.word)?p.currentLookup:null;const saved=await api('save',{id:savingId,word:p.word,meaning:p.meaning,primaryMeaning:p.meaning,example:p.example,note:p.note,source:d?.source||'自行記錄',sourceUrl:d?.sourceUrl||'',phonetic:d?.phonetic||'',dictionaryNotes:d?.dictionaryNotes||(d?.senses||[]).map(s=>[s.part,s.meaning,s.english].filter(Boolean).join(' · ')).join('\n')});await refresh();const unchanged=editId===savingId&&['word','meaning','example','note'].every(k=>$('#'+k).value===p[k]);if(unchanged){clearEdit();status('#form-status',`${saved.word} · ${saved.meaning} 已${savingId?'更新':'加入'}。可以輸入下一個單字。`);$('#saved-actions').hidden=false;$('#word').focus();}else toast(saved.word+' 已儲存，目前填寫的內容已保留。');},e.submitter,'#form-status');};
$('#saved-review').onclick=()=>startReview(false);
function editCard(c){editId=c.id;version++;lookingUp=false;$('#save-form button.primary').disabled=false;$('#saved-actions').hidden=true;currentLookup={word:c.word,source:c.source,sourceUrl:c.sourceUrl,phonetic:c.phonetic,dictionaryNotes:c.dictionaryNotes,primaryMeaning:c.primaryMeaning};$('#word').value=c.word;$('#meaning').value=c.meaning;$('#example').value=c.example||'';$('#note').value=c.note||'';$('#lookup-result').innerHTML='';$('#edit-title').textContent='修改 '+c.word;$('#save-form button.primary').textContent='儲存修改';renderLookup(currentLookup);$('#extras').open=false;status('#form-status','更新這張小卡會保留複習進度；更換單字則重新學習。');saveDraft();view('add');}
function renderLibrary(){
 const counts={all:state.cards.length,0:0,1:0,2:0,3:0};state.cards.forEach(c=>{const r=cardRating(c);if(r!==null)counts[r]++;});
 const filters=[['all','全部'],['0','非常困難'],['1','困難'],['2','尚可'],['3','簡單']];$('#library-filters').innerHTML=filters.map(([key,label])=>`<button type="button" data-library-filter="${key}" aria-pressed="${libraryFilter===key}">${label}<span>${counts[key]}</span></button>`).join('');document.querySelectorAll('[data-library-filter]').forEach(b=>b.onclick=()=>{libraryFilter=b.dataset.libraryFilter;renderLibrary();});
 const q=$('#filter').value.trim().toLowerCase(),selected=libraryFilter==='all'?[...state.cards]:state.cards.filter(c=>cardRating(c)===Number(libraryFilter)),cards=selected.filter(c=>[c.word,c.meaning,c.dictionaryNotes,c.note,c.example].join(' ').toLowerCase().includes(q)),wordCount=new Set(cards.map(c=>c.word)).size;$('#library-count').textContent=q?`找到 ${wordCount} 個單字`:libraryFilter==='all'?`全部已收集 ${wordCount} 個單字`:`${filters.find(f=>f[0]===libraryFilter)[1]} · ${wordCount} 個單字`;
 $('#cards').innerHTML=cards.length?cards.map(c=>{const r=cardRating(c);return `<article class="entry"><div><div class="entry-title"><h2>${esc(c.word)}</h2><button type="button" class="speaker" data-list-speak="${c.id}" aria-label="朗讀 ${esc(c.word)}" title="聽發音">${speakerIcon}</button>${r===null?'':`<span class="level-chip rating-${r}">上次評分：${labels[r]}</span>`}</div><p>${esc(meanings(c).main)}</p>${c.example?'<p class="muted">'+esc(c.example)+'</p>':''}${c.note?'<p class="small">筆記：'+esc(c.note)+'</p>':''}<p class="source">${source(c)} · 練習 ${c.reviews} 次 · ${c.due<=Date.now()?'現在可複習':'下次 '+date(c.due)}</p>${c.dictionaryNotes?'<details><summary>全部字典解釋</summary><p class="small prewrap">'+esc(c.dictionaryNotes)+'</p></details>':''}</div><div class="actions"><button class="secondary" data-edit="${c.id}" aria-label="編輯 ${esc(c.word)}">編輯</button><button class="secondary" data-delete="${c.id}" aria-label="移到回收區 ${esc(c.word)}">移到回收區</button></div></article>`;}).join(''):'<div class="empty">'+(q?'這個分類中沒有符合搜尋的單字。':libraryFilter==='all'?'還沒有單字。從你今天遇到的第一個字開始吧。':'目前沒有「'+filters.find(f=>f[0]===libraryFilter)[1]+'」的單字。')+'</div>';
 document.querySelectorAll('[data-list-speak]').forEach(b=>b.onclick=()=>speak(state.cards.find(c=>c.id===b.dataset.listSpeak).word));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editCard(state.cards.find(c=>c.id===b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>run(async()=>{await api('delete',{id:b.dataset.delete});queue=queue.filter(id=>id!==b.dataset.delete);await refresh();status('#library-status','已移到回收區；可在下方立即還原。');},b,'#library-status'));
 $('#trash').hidden=!state.trash.length;$('#trash').innerHTML=state.trash.length?'<details><summary>回收區 · '+state.trash.length+' 個單字（可還原）</summary>'+state.trash.map(c=>`<div class="trash-row"><span>${esc(c.word)} · ${esc(c.meaning)}</span><button class="secondary" data-restore="${c.id}">還原 ${esc(c.word)}</button></div>`).join('')+'</details>':'';document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>run(async()=>{await api('restore',{id:b.dataset.restore});await refresh();status('#library-status','已還原單字與原來的複習進度。');},b,'#library-status'));
}
$('#filter').oninput=renderLibrary;
async function startReview(p=false){await run(async()=>{await refresh();if(!state.cards.length){view('add');$('#word').focus();return;}if(session&&queue.length&&practice===p){view('review');showReview();return;}practice=p;queue=(practice?state.cards:due()).slice(0,20).map(c=>c.id);sessionTotal=queue.length;session=queue.length>0;view('review');showReview();},$('#start-review'));}
$('#start-review').onclick=()=>startReview(false);$('#practice-review').onclick=()=>startReview(true);$('#review-mode').onchange=showReview;
function intervalLabel(c,r){return r===0?'10 分鐘後':Math.round(Math.min(365,interval(c,r))*10)/10+' 天後';}
function speak(w){if(!('speechSynthesis'in window)){toast('這個瀏覽器不支援朗讀。');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w);u.lang='en-US';u.rate=.85;u.onerror=e=>{if(!['canceled','interrupted'].includes(e.error))toast('無法播放系統英文語音，請檢查裝置音量或語音設定。');};speechSynthesis.speak(u);}
function showReview(){
 answered=false;ratingBusy=false;status('#review-status','');$('#rating-buttons').hidden=true;const c=state.cards.find(c=>c.id===queue[0]);$('#review-progress').textContent=`${practice?'自由練習 · 不改變排程':'到期複習'} · 本輪 ${sessionTotal-queue.length} / ${sessionTotal}`;
 if(!c){session=false;stats();$('#review-card').innerHTML=`<div class="eyebrow">${sessionTotal?'WELL DONE':'ALL CAUGHT UP'}</div><h2>${sessionTotal?'這一輪完成了。':'目前沒有到期單字。'}</h2><p class="muted">${practice?'這次自由練習沒有更動正式複習進度。':due().length?'還有 '+due().length+' 張待複習，可繼續下一輪。':esc(nextDue())}</p><div class="actions review-actions"><button id="back-home" class="primary">回到今日學習</button>${!practice&&due().length?'<button id="next-round" class="secondary">繼續下一輪</button>':''}${state.cards.length?'<button id="practice-again" class="secondary">自由練習這些單字</button>':''}</div>`;$('#back-home').onclick=()=>view('home');if($('#next-round'))$('#next-round').onclick=()=>startReview(false);if($('#practice-again'))$('#practice-again').onclick=()=>{session=false;startReview(true);};return;}
 const re=new RegExp('(?<![a-z])'+c.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?![a-z])','gi'),cloze=$('#review-mode').value==='cloze'&&c.example&&re.test(c.example);re.lastIndex=0;
 const m=meanings(c);
 $('#review-card').innerHTML='<span class="eyebrow">'+(cloze?'補上句子裡缺少的單字':'先回想意思，再看答案')+'</span><div class="word-heading review-heading"><div class="review-word">'+esc(cloze?c.example.replace(re,'________'):c.word)+'</div>'+(!cloze?audioButton('speak',c.word):'')+'</div><div class="answer" id="answer" hidden>'+(cloze?'<div class="word-heading"><h2>'+esc(c.word)+'</h2>'+audioButton('answer-speak',c.word)+'</div>':'')+'<p class="compact-meaning">'+esc(m.main)+'</p>'+(m.extra?'<p class="context-meaning">特定用法／待核對：'+esc(m.extra)+'</p>':'')+'<details class="review-extras"><summary>補充內容</summary>'+(c.example?'<p>'+esc(c.example)+'</p>':'')+(c.note?'<p class="muted">'+esc(c.note)+'</p>':'')+'<p class="source">'+source(c)+'</p>'+(c.dictionaryNotes?'<details><summary>字典原始解釋</summary><p class="small prewrap">'+esc(c.dictionaryNotes)+'</p></details>':'')+'</details></div><div class="actions review-actions"><button id="reveal" class="primary">翻開答案</button></div>';
 if($('#review-mode').value==='cloze'&&!cloze)$('#review-card').insertAdjacentHTML('afterbegin','<p class="small muted">尚無包含原字的例句，這張先看英文回想。</p>');
 if($('#answer-speak'))$('#answer-speak').onclick=()=>speak(c.word);
 if($('#speak'))$('#speak').onclick=()=>speak(c.word);$('#reveal').onclick=()=>reveal(c);$('#reveal').focus({preventScroll:true});
}
function reveal(c){answered=true;$('#answer').hidden=false;$('#reveal').hidden=true;$('#rating-buttons').hidden=false;$('#rating-buttons').innerHTML=labels.map((l,i)=>`<button data-rating="${i}"><b>${i+1}. ${l}</b><small>${descriptions[i]}</small><span>${practice?'自由練習 · 不改排程':intervalLabel(c,i)}</span></button>`).join('');document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>rate(c,Number(b.dataset.rating)));$('#rating-buttons').scrollIntoView({block:'nearest',behavior:'instant'});$('#rating-buttons button').focus({preventScroll:true});}
function rate(c,rating){if(ratingBusy||!answered)return;ratingBusy=true;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=true);run(async()=>{if(!practice){const saved=await api('review',{id:c.id,rating});state.cards=state.cards.map(x=>x.id===c.id?saved:x);state.history.push({id:c.id,day:today(),at:saved.lastReview||Date.now(),rating});renderLibrary();}queue.shift();stats();showReview();},null,'#review-status').finally(()=>{ratingBusy=false;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=false);});}
document.addEventListener('keydown',e=>{if(active!=='review'||e.ctrlKey||e.altKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(answered&&/^[1-4]$/.test(e.key)){e.preventDefault();const c=state.cards.find(c=>c.id===queue[0]);if(c)rate(c,Number(e.key)-1);}});
function readingText(text){return readingParts(text).map(p=>p.word?`<button type="button" class="reading-word" data-reading-word="${esc(p.word)}">${esc(p.text)}</button>`:esc(p.text)).join('');}
function renderReadingLookup(d){
 const notes=(d.senses||[]).map(s=>[s.part,s.meaning,s.english].filter(Boolean).join(' · ')).join('\n'),m=meanings({...d,dictionaryNotes:notes});
 $('#reading-translation').innerHTML=`<div class="word-heading"><h3>${esc(d.word)}</h3>${audioButton('reading-speak',d.word)}</div>${d.phonetic?`<p class="source">${esc(d.phonetic)}</p>`:''}<p class="reading-meaning">${esc(m.main||'內建字典找不到這個字。')}</p>${m.extra?`<p class="small muted">其他用法：${esc(m.extra)}</p>`:''}<div class="actions"><button type="button" id="collect-reading-word" class="primary">${state.cards.some(c=>c.word===d.word)?'查看這張單字卡':'收進單字本'}</button></div><p class="source">${source(d)}</p>`;
 $('#reading-translation').hidden=false;$('#reading-speak').onclick=()=>speak(d.word);$('#collect-reading-word').onclick=()=>{clearEdit();currentLookup={...d,dictionaryNotes:notes};$('#word').value=d.word;$('#example').value=readingContext(article.text,d.word);$('#note').value='閱讀來源：'+article.title+'\n'+article.url;renderLookup(currentLookup);saveDraft();view('add');};
}
let readingLookupVersion=0;
async function lookupReadingWord(word,button){
 const v=++readingLookupVersion;document.querySelectorAll('[data-reading-word]').forEach(b=>b.classList.toggle('selected',b===button));$('#reading-translation').hidden=false;$('#reading-translation').innerHTML=`<p class="muted">正在查詢 <b>${esc(word)}</b>…</p>`;
 try{const d=await api('lookup?word='+encodeURIComponent(word));if(v===readingLookupVersion)renderReadingLookup(d);}catch(e){if(v===readingLookupVersion)$('#reading-translation').innerHTML=`<p class="notice error">${esc(e.message)}</p>`;}
}
function renderNews(){
 if(!article)return;
 $('#news').innerHTML=`<div class="reading-toolbar"><span class="eyebrow">NASA · DAILY READING</span><button type="button" id="toggle-translation" class="inline-translate-btn">${article.zh&&showArticleZh?'隱藏中文':'顯示中文'}</button></div><h2>${esc(article.title)}</h2><p class="source">發布：${esc(new Date(article.published).toLocaleDateString('zh-TW'))} · 選讀：${esc(article.day)} · ${esc(article.source)}</p><p class="notice">${esc(article.notice)}</p><p class="reading-instruction">點一下不懂的英文單字</p><p class="reading-text">${readingText(article.text)}</p><div id="reading-translation" class="reading-translation" role="status" aria-live="polite" hidden></div>${article.zh?`<section class="inline-translation" ${showArticleZh?'':'hidden'} aria-label="中文翻譯"><span class="eyebrow">繁體中文 · ${esc(article.translationProvider||'機器翻譯')}</span><h3>${esc(article.zhTitle)}</h3><p>${esc(article.zh)}</p></section>`:''}<div class="article-links"><a href="${safeLink(article.url)}" target="_blank" rel="noopener">到 NASA 閱讀英文原文 ↗</a></div><p id="news-status" class="notice" role="status" hidden></p>`;
 document.querySelectorAll('[data-reading-word]').forEach(b=>b.onclick=()=>lookupReadingWord(b.dataset.readingWord,b));
 $('#toggle-translation').onclick=e=>{if(article.zh){showArticleZh=!showArticleZh;renderNews();return;}run(async()=>{try{article=await api('news/translate',{});}catch{article=await translateReadingInBrowser(article);}showArticleZh=true;renderNews();},e.target,'#news-status');};
}
function renderHomeReading(){
 if(!article)return;const words=String(article.text||'').trim().split(/\s+/).filter(Boolean),minutes=Math.max(1,Math.ceil(words.length/180)),average=words.length?words.reduce((sum,w)=>sum+w.replace(/[^a-z]/gi,'').length,0)/words.length:0,level=average>5.4?'較有挑戰':average>4.7?'中等':'輕鬆';
 $('#home-reading-title').textContent=article.title;$('#home-reading-zh').textContent=article.zhTitle||'點進文章後可顯示整篇中文翻譯。';$('#reading-minutes').textContent=minutes;$('#reading-level').textContent=level;
}
async function translateReadingInBrowser(item){
 const chunks=text=>{const out=[];for(const paragraph of String(text||'').split(/\n{2,}/)){let rest=paragraph.trim();while(rest.length>1800){let end=rest.lastIndexOf(' ',1800);if(end<1100)end=1800;out.push(rest.slice(0,end));rest=rest.slice(end).trim();}if(rest)out.push(rest);}return out;},values=[];
 for(const text of [item.title,item.text]){const translated=[];for(const chunk of chunks(text)){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-TW&dt=t&q='+encodeURIComponent(chunk),{signal:controller.signal});if(!r.ok)throw Error('中文翻譯暫時無法使用，請稍後再試。');const d=await r.json(),value=Array.isArray(d?.[0])?d[0].map(x=>Array.isArray(x)?x[0]||'':'').join('').trim():'';if(!value)throw Error('中文翻譯暫時無法使用，請稍後再試。');translated.push(value);}finally{clearTimeout(timer);}}values.push(translated.join('\n\n'));}
 return {...item,zhTitle:values[0],zh:values[1],translationProvider:'Google 翻譯'};
}
let newsLoading=false;
async function loadNews(){if(newsLoading)return;newsLoading=true;try{article=await api('news');renderNews();renderHomeReading();}catch(e){$('#news').innerHTML='<p class="notice error">'+esc(e.message)+'</p><button id="retry-news" class="secondary">重新載入</button>';$('#retry-news').onclick=loadNews;$('#home-reading-title').textContent='今天的文章暫時無法載入';$('#home-reading-zh').textContent='請稍後再試，已收集的單字與複習進度不受影響。';}finally{newsLoading=false;}}
$('#settings-form').onsubmit=e=>{e.preventDefault();run(async()=>{const b={};if($('#mw-key').value.trim())b.mw=$('#mw-key').value.trim();if($('#deepl-key').value.trim())b.deepl=$('#deepl-key').value.trim();if(!Object.keys(b).length){status('#settings-status','沒有輸入新金鑰，原設定保持不變。');return;}await api('settings',b);$('#settings-form').reset();await refresh();status('#settings-status','設定已保存。請查詢單字或翻譯文章，以確認金鑰有效。');},e.submitter,'#settings-status');};
$('#disconnect').onclick=e=>run(async()=>{await api('settings',{mw:'',deepl:''});await refresh();status('#settings-status','已移除服務金鑰。');},e.target,'#settings-status');
$('#export').onclick=e=>run(async()=>{const saved=await api('backup',{});status('#backup-status',saved.cloud?'已準備 '+saved.backup.cards.length+' 個單字與複習紀錄，瀏覽器將下載備份。備份不包含金鑰與回收區。':'已保存 '+saved.backup.cards.length+' 個單字與複習紀錄。備份位置：'+saved.path+'。也已嘗試讓瀏覽器下載一份；若沒有下載，可從上述位置取用。備份不包含金鑰與回收區。');const blob=new Blob([JSON.stringify(saved.backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='拾字備份-'+today()+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);},e.target,'#backup-status');
$('#import-button').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#import').click();}};
$('#import').onchange=e=>run(async()=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error('備份太大，請選擇小於 5 MB 的檔案。');let d;try{d=JSON.parse(await f.text());}catch{throw Error('這不是有效的 JSON 備份檔，請選擇由拾字匯出的備份。');}const r=await api('import',d);await refresh();status('#backup-status',`匯入完成：新增 ${r.added} 個單字、${r.historyAdded} 筆複習紀錄。重複內容已略過。`);}finally{e.target.value='';}},null,'#backup-status');
try{const d=JSON.parse(localStorage.getItem('word-garden-draft')||'null');if(d&&typeof d.word==='string'){['word','meaning','example','note'].forEach(k=>$('#'+k).value=String(d[k]||''));lastDraftWord=norm(d.word);editId=d.editId||null;currentLookup=d.currentLookup||null;if(editId){$('#edit-title').textContent='繼續修改 '+d.word;$('#save-form button.primary').textContent='儲存修改';}if(d.word){if(currentLookup)renderLookup(currentLookup);else if(d.meaning){$('#save-form').hidden=false;$('#extras').open=true;$('#manual-meaning').open=true;}status('#form-status','已恢復上次尚未儲存的內容。');}}}catch{}
run(async()=>{await refresh();if(currentLookup)renderLookup(currentLookup);status('#connection-status','');loadNews();},null,'#connection-status');
setInterval(()=>{stats();if(active==='library')renderLibrary();},30000);
